on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildJava:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'adopt'
    - name: Compile with JavaC
      run: javac -encoding utf-8 $(find . -type f -name "*.java")

  buildHaskell:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install GHC
      run: sudo apt install ghc -y
    - name: Compile with GHC
      run: ghc $(find . -type f -name "*.hs")

  buildScala:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Get to correct directory
      run: cd src/day3
    - name: Compile Scala with SBT
      run: sbt compile
