on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildJava:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'adopt'
    - name: Compile with JavaC
      run: javac -encoding utf-8 $(find . -type f -name "*.java")

  buildHaskell:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install GHC
      run: sudo apt install ghc -y
    - name: Compile with GHC
      run: ghc $(find . -type f -name "*.hs")

  buildScala:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Compile Scala with SBT
      run: cd src/day3 && sbt compile

  buildLUA:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Install LUA
      run: sudo apt install lua5.3 -y
    - name: Run, since not compiled
      run: cd src/day4 && pwd && lua day4.lua

  buildDotNet:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
          dotnet-version: '7.0.100'
    - name: Build dotnet
      run: cd src/day5/ && pwd && dotnet build

  buildNodeJS:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup NodeJSä
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: npm
    - name: Run, since not compiled
      run: cd src/day6/ && pwd && node day6.js
