on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildJava:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'adopt'
    - name: Compile with JavaC
      run: javac -encoding utf-8 $(find . -type f -name "*.java")

  buildHaskell:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install GHC
      run: sudo apt install ghc -y
    - name: Compile with GHC
      run: ghc $(find . -type f -name "*.hs")

  buildScala:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Compile Scala with SBT
      run: cd src/day3 && sbt compile

  buildLUA:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Install LUA
      run: sudo apt install lua5.3 -y
    - name: Run, since not compiled
      run: cd src/day4 && pwd && lua day4.lua

  buildDotNet:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
          dotnet-version: '7.0.100'
    - name: Build dotnet day 5
      run: cd src/day5/ && pwd && dotnet build
    - name: Build dotnet day 11
      run: cd src/day11/ && pwd && dotnet build

  buildNodeJS:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup NodeJS
      run: sudo apt install nodejs -y
    - name: Run day 6, since not compiled
      run: cd src/day6/ && pwd && node day6.js
    - name: Run day 13, since not compiled
      run: cd src/day13/ && pwd && node day13.js
      
  buildTypeScript:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup NodeJS
      run: sudo apt install nodejs -y
    - name: Install typescript
      run: npm install typescript -g
    - name: Install node types
      run: npm i @types/node -g
    - name: Transpile TypeScript
      run: cd src/day7/ && pwd && tsc day7.ts

  buildPython:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup python3
      run: sudo apt install python3 -y
    - name: Run since not compiled
      run: cd src/day8/ && pwd && python3 day8.py

  buildC:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: install GCC
      run: sudo apt install gcc -y
    - name: compile c code
      run: gcc $(find . -type f -name "*.c")
